# Generated by Django 4.2.2 on 2024-01-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_delete_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='body_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
