# Generated by Django 4.2.2 on 2024-01-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_body_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='body_text',
            new_name='body_text_1',
        ),
        migrations.AddField(
            model_name='project',
            name='body_text_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='body_text_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
