# Generated by Django 4.2.2 on 2024-01-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_academicexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicexperience',
            name='location',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
