# Generated by Django 4.2.2 on 2024-01-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_links_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='links',
            name='logo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
